export const DISPLAY_ALERT: string = "DISPLAY_ALERT";
export const CLEAR_ALERT: string = "CLEAR_ALERT";
export const SETUP_USER_BEGIN: string = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS: string = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR: string = "SETUP_USER_ERROR";
export const GET_CURRENT_USER_BEGIN: string = "GET_CURRENT_USER_BEGIN";
export const GET_CURRENT_USER_SUCCESS: string = "GET_CURRENT_USER_SUCCESS";
export const LOGOUT_USER: string = "LOGOUT_USER";
export const TOGGLE_SIDEBAR: string = "TOGGLE_SIDEBAR";
export const HANDLE_CHANGE: string = "HANDLE_CHANGE";
export const CREATE_JOB_BEGIN: string = "CREATE_JOB_BEGIN";
export const CREATE_JOB_SUCCESS: string = "CREATE_JOB_SUCCESS";
export const CREATE_JOB_ERROR: string = "CREATE_JOB_ERROR";
export const CLEAR_VALUES: string = "CLEAR_VALUES";
export const GET_ALL_COMPANY_JOBS_BEGIN: string = "GET_ALL_COMPANY_JOBS_BEGIN";
export const GET_ALL_COMPANY_JOBS_SUCCESS: string =
  "GET_ALL_COMPANY_JOBS_SUCCESS";
export const GET_ALL_COMPANY_JOBS_ERROR: string = "GET_ALL_COMPANY_JOBS_ERROR";
export const DELETE_JOB_BEGIN: string = "DELETE_JOB_BEGIN";
export const DELETE_JOB_ERROR: string = "DELETE_JOB_ERROR";
export const GET_APPLICANTS_BEGIN: string = "GET_APPLICANTS_BEGIN";
export const GET_APPLICANTS_SUCCESS: string = "GET_APPLICANTS_SUCCESS";
export const GET_APPLICANTS_ERROR: string = "GET_APPLICANTS_ERROR";
export const TOGGLE_APPLICANTS: string = "TOGGLE_APPLICANTS";
export const UPDATE_STATUS_BEGIN: string = "UPDATE_STATUS_BEGIN";
export const UPDATE_STATUS_SUCCESS: string = "UPDATE_STATUS_SUCCESS";
export const UPDATE_STATUS_ERROR: string = "UPDATE_STATUS_ERROR";
export const CREATE_INTERVIEW_BEGIN: string = "CREATE_INTERVIEW_BEGIN";
export const CREATE_INTERVIEW_SUCCESS: string = "CREATE_INTERVIEW_SUCCESS";
export const CREATE_INTERVIEW_ERROR: string = "CREATE_INTERVIEW_ERROR";
export const GET_ALL_INTERVIEWS_BEGIN: string = "GET_ALL_INTERVIEWS_BEGIN";
export const GET_ALL_INTERVIEWS_SUCCESS: string = "GET_ALL_INTERVIEWS_SUCCESS";
export const GET_ALL_INTERVIEWS_ERROR: string = "GET_ALL_INTERVIEWS_ERROR";
export const DELETE_INTERVIEW_BEGIN: string = "DELETE_INTERVIEW_BEGIN";
export const DELETE_INTERVIEW_ERROR: string = "DELETE_INTERVIEW_ERROR";
export const CLEAR_APPLICANTS: string = "CLEAR_APPLICANTS";
export const SET_EDIT_INTERVIEW: string = "SET_EDIT_INTERVIEW";
export const EDIT_INTERVIEW_BEGIN: string = "EDIT_INTERVIEW_BEGIN";
export const EDIT_INTERVIEW_SUCCESS: string = "EDIT_INTERVIEW_SUCCESS";
export const EDIT_INTERVIEW_ERROR: string = "EDIT_INTERVIEW_ERROR";
export const GET_ALL_JOBS_BEGIN: string = "GET_ALL_JOBS_BEGIN";
export const GET_ALL_JOBS_SUCCESS: string = "GET_ALL_JOBS_SUCCESS";
export const GET_ALL_JOBS_ERROR: string = "GET_ALL_JOBS_ERROR";
export const SET_COMPANY_ID: string = "SET_COMPANY_ID";
export const HANDLE_ADD_CERTIFICATION: string = "HANDLE_ADD_CERTIFICATION";
export const HANDLE_REMOVE_CERTIFICATION: string =
  "HANDLE_REMOVE_CERTIFICATION";
export const CREATE_APPLICATION_BEGIN: string = "CREATE_APPLICATION_BEGIN";
export const CREATE_APPLICATION_SUCCESS: string = "CREATE_APPLICATION_SUCCESS";
export const CREATE_APPLICATION_ERROR: string = "CREATE_APPLICATION_ERROR";
export const GET_ALL_APPLICATIONS_BEGIN: string = "GET_ALL_APPLICATIONS_BEGIN";
export const GET_ALL_APPLICATIONS_SUCCESS: string =
  "GET_ALL_APPLICATIONS_SUCCESS";
export const GET_ALL_APPLICATIONS_ERROR: string = "GET_ALL_APPLICATIONS_ERROR";
export const DELETE_APPLICATION_BEGIN: string = "DELETE_APPLICATION_BEGIN";
export const DELETE_APPLICATION_ERROR: string = "DELETE_APPLICATION_ERROR";
export const GET_ALL_USER_INTERVIEWS_BEGIN: string =
  "GET_ALL_USER_INTERVIEWS_BEGIN";
export const GET_ALL_USER_INTERVIEWS_SUCCESS: string =
  "GET_ALL_USER_INTERVIEWS_SUCCESS";
export const GET_ALL_USER_INTERVIEWS_ERROR: string =
  "GET_ALL_USER_INTERVIEWS_ERROR";
export const UPDATE_INTERVIEW_STATUS_BEGIN: string =
  "UPDATE_INTERVIEW_STATUS_BEGIN";
export const UPDATE_INTERVIEW_STATUS_SUCCESS: string =
  "UPDATE_INTERVIEW_STATUS_SUCCESS";
export const UPDATE_INTERVIEW_STATUS_ERROR: string =
  "UPDATE_INTERVIEW_STATUS_ERROR";
